version: "3.9"

services:
  rentalx-db:
    image: mysql:5.6
    container_name: db-rentalx
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=myrootpassword
      - MYSQL_DATABASE=rentalx
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=ignite
    volumes:
      - ../database:/var/lib/mysql
  app:
    build: .
    container_name: rentalx
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    links:
      - rentalx-db
    depends_on:
      - rentalx-db
